
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 21PROGA138
 */
public class autores extends javax.swing.JFrame {

    /**
     * Creates new form autores
     */
    public autores() {
        initComponents();
        this.getContentPane().setBackground(Color.gray);
        setIconImage(getIconImage());
        setLocationRelativeTo(null);
    }
    @Override 
    public Image getIconImage(){
        Image imagen =Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono.png"));
        return imagen;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblAutor1 = new javax.swing.JLabel();
        lblAutor2 = new javax.swing.JLabel();
        lblNomAutor1 = new javax.swing.JLabel();
        lblnomAutor2 = new javax.swing.JLabel();
        lblSemestreYgrupAutor1 = new javax.swing.JLabel();
        lblmatricAutor1 = new javax.swing.JLabel();
        lblSemestreYgrupAutor2 = new javax.swing.JLabel();
        lblMatricAutor2 = new javax.swing.JLabel();
        lblEspecialidadAutor1 = new javax.swing.JLabel();
        lblEspecialidadAutor2 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Autores");

        lblAutor1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblAutor1.setForeground(new java.awt.Color(255, 255, 255));
        lblAutor1.setText("Autor 1");

        lblAutor2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblAutor2.setForeground(new java.awt.Color(255, 255, 255));
        lblAutor2.setText("Autor 2");

        lblNomAutor1.setForeground(new java.awt.Color(255, 255, 255));
        lblNomAutor1.setText("Baldo Antonio Cruz Lopez ");

        lblnomAutor2.setForeground(new java.awt.Color(255, 255, 255));
        lblnomAutor2.setText("Marcos Julian Guemez Cuiriz");

        lblSemestreYgrupAutor1.setForeground(new java.awt.Color(255, 255, 255));
        lblSemestreYgrupAutor1.setText("3 semestre  grupo 'A'");

        lblmatricAutor1.setForeground(new java.awt.Color(255, 255, 255));
        lblmatricAutor1.setText("Matricula: 21316050940243 ");

        lblSemestreYgrupAutor2.setForeground(new java.awt.Color(255, 255, 255));
        lblSemestreYgrupAutor2.setText("3 semestre  grupo 'A'");

        lblMatricAutor2.setForeground(new java.awt.Color(255, 255, 255));
        lblMatricAutor2.setText("Matricula:20316050940185");

        lblEspecialidadAutor1.setForeground(new java.awt.Color(255, 255, 255));
        lblEspecialidadAutor1.setText("Especialidad en programacion");

        lblEspecialidadAutor2.setForeground(new java.awt.Color(255, 255, 255));
        lblEspecialidadAutor2.setText("Especialidad en programacion");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAutor1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomAutor1)
                    .addComponent(lblSemestreYgrupAutor1)
                    .addComponent(lblmatricAutor1)
                    .addComponent(lblEspecialidadAutor1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAutor2)
                    .addComponent(lblnomAutor2)
                    .addComponent(lblSemestreYgrupAutor2)
                    .addComponent(lblMatricAutor2)
                    .addComponent(lblEspecialidadAutor2))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutor1)
                    .addComponent(lblAutor2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomAutor1)
                    .addComponent(lblnomAutor2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemestreYgrupAutor1)
                    .addComponent(lblSemestreYgrupAutor2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmatricAutor1)
                    .addComponent(lblMatricAutor2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspecialidadAutor1)
                    .addComponent(lblEspecialidadAutor2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(autores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(autores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(autores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(autores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new autores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAutor1;
    private javax.swing.JLabel lblAutor2;
    private javax.swing.JLabel lblEspecialidadAutor1;
    private javax.swing.JLabel lblEspecialidadAutor2;
    private javax.swing.JLabel lblMatricAutor2;
    private javax.swing.JLabel lblNomAutor1;
    private javax.swing.JLabel lblSemestreYgrupAutor1;
    private javax.swing.JLabel lblSemestreYgrupAutor2;
    private javax.swing.JLabel lblmatricAutor1;
    private javax.swing.JLabel lblnomAutor2;
    // End of variables declaration//GEN-END:variables
}
